version: '3.4'
services:
    goerli-geth.dnp.dappnode.eth:
        image: 'goerli-geth.dnp.dappnode.eth:0.2.2'
        build: ./build
        volumes:
            - 'goerli:/goerli'
        ports:
            - '53535:30303'
            - '53535:30303/udp'
            - '53534:30304/udp'
volumes:
    goerli: {}
